config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  root 'main#index'

  post 'main/find', to: 'main#find',
      constraints: { format: :json }

  get 'main/vote_up/:id', to: 'main#vote_up'
  get 'main/vote_down/:id', to: 'main#vote_down'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :topics

end

app/models/concerns/karma.rb
module Karma
  extend ActiveSupport::Concern

  included do

    def up_karma!
      self.karma += 1
      self.save!
    end

    def down_karma!
      self.karma -= 1
      self.save!
    end

  end

end

app/models/concerns/presenter.rb
module Presenter
  include ActionView::Helpers::TextHelper
  extend ActiveSupport::Concern

  included do

    def teaser(keywords)
      result = ""
      self.body.gsub(/[.?!]/, '\0|').split("|").map(&:strip).each do |sentence|
        result += "#{highlight(sentence, keywords)}" if keywords.any? { |kword| sentence.downcase.include?(kword.downcase) }
      end
      result
    end

  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Presenter
  include Karma
  include PgSearch

  belongs_to :category
  pg_search_scope :proceed_search, against: [:title, :body], using: {tsearch: {prefix: true}}

  scope :with_category, lambda { |category_id| where(category_id: category_id) }

  default_scope { order('karma DESC') }

  def as_json(options={})
    super({ only: [:title, :original_uri, :id] }.merge(options)).tap do |json|
      json[:teaser] = self.teaser(options[:search_q].split(' '))
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @categories = Category.all
  end

  def find
    respond_to do |format|
      format.json { render json: fetch_topics_json }
    end
  end

  def vote_up
    Topic.find(params[:id]).try(:up_karma!)
    redirect_to root_path
  end

  def vote_down
    Topic.find(params[:id]).try(:down_karma!)
    redirect_to root_path
  end

  private

  def fetch_topics_json
    if params[:category].present?
      return Topic.proceed_search(params[:keywords]).with_category(params[:category]).as_json(search_q: params[:keywords])
    end
    Topic.proceed_search(params[:keywords]).as_json(search_q: params[:keywords])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Scraper"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Scraper

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; RailsFun Company 2015

app/views/main/index.html.haml
%h1
  = t(:title)
%div
  = form_tag(main_find_path, remote: true, id: 'search_form') do
    .form-group
      %label
        = t(:search_category)
      = select_tag(:category, options_from_collection_for_select(@categories, :id, :name), {class: 'form-control', include_blank: true})
    .form-group
      %label
        = t(:search_label)
      %input.form-control{type: :text, name: :keywords}
    = submit_tag(t(:find), {class: 'btn btn-primary btn-lg'})
.results-wrapper